<template>
  <header>
    <div>
      <h1>
        <routerlink></routerlink>
      </h1>
      <ul>
        <li>
          <routerlink><span></span><span></span></routerlink>
        </li>
        <li>
          <routerlink><span></span><span></span></routerlink>
        </li>
        <li>
          <routerlink><span></span><span></span></routerlink>
        </li>
        <li>
          <routerlink><span></span><span></span></routerlink>
        </li>
      </ul>
    </div>
    <ul>
      <li>
        <routerlink></routerlink>
      </li>
      <li>
        <routerlink></routerlink>
      </li>
      <li>
        <routerlink></routerlink>
      </li>
    </ul>
  </header>
</template>
